"""Add CCTV and Road Hazards

Revision ID: 4b979f3c6637
Revises: e76c97c546b3
Create Date: 2026-09-26 13:36:14.393267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '4b979f3c6637'
down_revision: Union[str, Sequence[str], None] = 'e76c97c546b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cctv_cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('camera_type', sa.Enum('TRAFFIC', 'PUBLIC_SURVEILLANCE', 'GOVERNMENT', name='cameratype'), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=False),
    sa.Column('data_type', sa.Enum('OFFICIAL', 'OPEN_DATA', 'THIRD_PARTY_API', 'CALCULATED', 'USER_REPORTED', 'ESTIMATED', name='datasourcetype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cctv_cameras_camera_type'), 'cctv_cameras', ['camera_type'], unique=False)
    op.create_index(op.f('ix_cctv_cameras_id'), 'cctv_cameras', ['id'], unique=False)
    
    op.create_table('road_hazards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('hazard_type', sa.Enum('POTHOLE', 'ROAD_DAMAGE', 'UNDER_CONSTRUCTION', 'UNPAVED_SURFACE', 'WATERLOGGED', name='hazardtype'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'VERIFIED', 'RESOLVED', name='hazardstatus'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=False),
    sa.Column('data_type', sa.Enum('OFFICIAL', 'OPEN_DATA', 'THIRD_PARTY_API', 'CALCULATED', 'USER_REPORTED', 'ESTIMATED', name='datasourcetype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_hazards_hazard_type'), 'road_hazards', ['hazard_type'], unique=False)
    op.create_index(op.f('ix_road_hazards_id'), 'road_hazards', ['id'], unique=False)
    op.create_index(op.f('ix_road_hazards_status'), 'road_hazards', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_road_hazards_status'), table_name='road_hazards')
    op.drop_index(op.f('ix_road_hazards_id'), table_name='road_hazards')
    op.drop_index(op.f('ix_road_hazards_hazard_type'), table_name='road_hazards')
    op.drop_table('road_hazards')
    op.drop_index(op.f('ix_cctv_cameras_id'), table_name='cctv_cameras')
    op.drop_index(op.f('ix_cctv_cameras_camera_type'), table_name='cctv_cameras')
    op.drop_table('cctv_cameras')
    
    op.execute("DROP TYPE IF EXISTS cameratype")
    op.execute("DROP TYPE IF EXISTS hazardtype")
    op.execute("DROP TYPE IF EXISTS hazardstatus")
    # ### end Alembic commands ###
