"""Add TransitHubs

Revision ID: e447044ca5f2
Revises: 4b979f3c6637
Create Date: 2026-09-26 14:00:20.894949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'e447044ca5f2'
down_revision: Union[str, Sequence[str], None] = '4b979f3c6637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transit_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hub_type', sa.Enum('BUS_TERMINAL', 'RAILWAY_STATION', name='transithubtype'), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=False),
    sa.Column('data_type', sa.Enum('OFFICIAL', 'OPEN_DATA', 'THIRD_PARTY_API', 'CALCULATED', 'USER_REPORTED', 'ESTIMATED', name='datasourcetype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_hubs_hub_type'), 'transit_hubs', ['hub_type'], unique=False)
    op.create_index(op.f('ix_transit_hubs_id'), 'transit_hubs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transit_hubs_id'), table_name='transit_hubs')
    op.drop_index(op.f('ix_transit_hubs_hub_type'), table_name='transit_hubs')
    op.drop_index('idx_transit_hubs_geom', table_name='transit_hubs', postgresql_using='gist')
    op.drop_table('transit_hubs')
    sa.Enum(name='transithubtype').drop(op.get_bind())
    # ### end Alembic commands ###
